#!/bin/sh
# Generated by gh-action-imagebuilder
# 以下三个占位符（LAN / PPPoE / root 密码）由 entrypoint.sh 在构建时替换

__LAN_BLOCK__

__PPPOE_BLOCK__

__ROOT_PW_BLOCK__

uci commit network

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface

# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''
uci commit

# 设置系统标识（ZeroWrt 版本信息）
FILE_PATH="/etc/openwrt_release"
sed -i "s/DISTRIB_DESCRIPTION='[^']*'/DISTRIB_DESCRIPTION='ZeroWrt-$(date +%Y%m%d)'/g" "$FILE_PATH"
sed -i "s/DISTRIB_REVISION='[^']*'/DISTRIB_REVISION=' By MinimaxFlora'/g" "$FILE_PATH"
sed -i "s|^OPENWRT_RELEASE=\".*\"|OPENWRT_RELEASE=\"ZeroWrt 标准版 @R$(date +%Y%m%d) BY MinimaxFlora\"|" /usr/lib/os-release

# 设置主机名
uci set system.@system[0].hostname='ZeroWrt'
uci commit system

# 换源：OpenWrt 官方源 -> 腾讯云镜像（加速软件包下载）
sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/openwrt,g' /etc/apk/repositories.d/distfeeds.list

exit 0
