#!/bin/sh
# Generated by gh-action-imagebuilder
# 以下三个占位符（LAN / PPPoE / root 密码）由 entrypoint.sh 在构建时替换

__LAN_BLOCK__

__PPPOE_BLOCK__

__ROOT_PW_BLOCK__

uci commit network

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface

# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''
uci commit

# 设置系统标识（ZeroWrt 版本信息）
FILE_PATH="/etc/openwrt_release"
sed -i "s/DISTRIB_DESCRIPTION='[^']*'/DISTRIB_DESCRIPTION='ZeroWrt-$(date +%Y%m%d)'/g" "$FILE_PATH"
sed -i "s/DISTRIB_REVISION='[^']*'/DISTRIB_REVISION=' By MinimaxFlora'/g" "$FILE_PATH"
sed -i "s|^OPENWRT_RELEASE=\".*\"|OPENWRT_RELEASE=\"ZeroWrt 标准版 @R$(date +%Y%m%d) BY MinimaxFlora\"|" /usr/lib/os-release

# 设置主机名
uci set system.@system[0].hostname='ZeroWrt'
uci commit system

# 换源：OpenWrt 官方源 -> 腾讯云镜像（加速软件包下载）
if [ -f /etc/apk/repositories.d/distfeeds.list ]; then
  sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/openwrt,g' /etc/apk/repositories.d/distfeeds.list
elif [ -f /etc/opkg/distfeeds.conf ]; then
  sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/openwrt,g' /etc/opkg/distfeeds.conf
fi

# 配置 Extras_Paclages 插件源（密钥已预置到镜像；首次开机网络未就绪，不做 update）
if command -v apk >/dev/null 2>&1; then
  # ---- OpenWrt 25.x (apk) ----
  echo "https://raw.githubusercontent.com/MinimaxFlora/Extras_Paclages/apk/$(cat /etc/apk/arch)/packages.adb" >> /etc/apk/repositories.d/customfeeds.list
elif command -v opkg >/dev/null 2>&1; then
  # ---- OpenWrt 24.x (opkg) ----
  . /etc/openwrt_release
  echo "src/gz openwrt_extras https://raw.githubusercontent.com/MinimaxFlora/Extras_Paclages/ipk/${DISTRIB_ARCH}" >> /etc/opkg/customfeeds.conf
fi

exit 0
